full_doc = ("In 1995, child psychologists Betty Hart and Todd Risley reported that by age three, children in higher-socio-economic-status households had heard 30 million more words than their counter-parts in lower-socioeconomic-status homes. This so-called word gap has often been invoked to explain why children in the former category tend to display better language skills and perform better in school compared to those from underprivileged homes—with effects that reverberate throughout their lives. "

"'Language is implicated in school achievement, social emotional growth, in health outcomes [and] in job outcomes when you're a grown-up,' says Roberta Golinkoff, who leads the Child's Play, Learning, and Development laboratory at the University of Delaware. 'Language predicts all these.' "

"But researchers have struggled to gain a mechanistic understanding of this phenomenon. 'What people are discovering is that socioeconomic status is really just a proxy variable,' says Rachel Romeo, a postdoc in developmental cognitive neuroscience at MIT and Boston Children's Hospital. Although factors such as household income and parental education are associated with a child's learning abilities, researchers suspect there are features of the home learning environment, such as the amount of time adults spend talking to their children, that have a more direct influence. But few studies have been able to measure these environmental effects on learning ability, as they are difficult to disentangle from a family's socioeconomic status, notes Romeo. "

"To dig deeper, she and her colleagues recently set out to determine the neural underpinnings of language ability differences across the socioeconomic spectrum. First, Romeo and her team measured the language exposure of 40 children between the ages of 4 and 6 from various backgrounds. Each child carried around an audio recorder for a single weekend in 2015 or 2016 within the pocket of a specially designed T-shirt, a setup that helped capture a child's language environment from his or her perspective. Then, the researchers used analytical software to count the number of conversational turns—one turn being measured as a pair of adult and child responses separated by five seconds or less—occurring over every hour for the 48-hour period. "

"Socioeconomic status is really just a proxy variable."

"—Rachel Romeo, MIT & Boston Children's Hospital "
"The team conducted the second part of their study back in the laboratory, where parents and children who had taken part in the recordings underwent MRI scans. In their analyses, Romeo and her colleagues specifically focused on white matter tracts, or the 'information highways' connecting different regions of the participants' brains, Romeo says. 'We were looking at the strength of these connections in various parts of the brain.' "

"The researchers found that tracts running between regions of the brain known to be important for language development in the left hemisphere had a more coherent structure in children who shared greater turn-taking with their parents. On average, those children had greater white matter connectivity between Broca's area and Wernicke's area, two regions associated with speech production and comprehension (J Neurosci, 38:7870–77, 2018). "

"The results indicate that two-way adult-child conversation—independent of the child's socioeconomic status and the number of words a child hears—can strengthen neural pathways involved in language. 'Our research suggests that it's not really the volume of language children hear, but really about the quality of the conversation—this back-and-forth dialogue,' says Romeo. "

"'This study has added an interesting additional variable that helps our explanatory power of why [lower socioeconomic status] might be associated with poor language outcomes,' says Rachel Barr, the director of Georgetown University's Early Learning Project, who was not involved in this study. She adds that parents in these families may have fewer opportunities to share dialogue with their children—and that interventions focused on conversational turn-taking could help. 'It's not just, ‘Add words, and the child's language will develop,'' she says. 'It's rather that language is a communication process, and the child needs to learn when it's their turn.'"

"Romeo says that 'there's been a lot of dissemination of research in the last couple of decades saying that children need to hear X amount of words a day. [It] creates sort of this phenomenon where parents are monologuing to their children and just saying words just to get them in—almost like there's a quota.' Golinkoff notes that it's also important to realize that ambient sounds from the TV or radio, like conversations that do not involve the child in turn-taking, may have little impact on the learning abilities of children."

"Romeo's advice: 'Instead of talking to your children, really try and talk with them; let them respond,' she says. 'Have an exchange of information rather than just a one-sided discussion.' ")